version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      ## Para Windows, coloque o caminho completo
      - D:/Eduzz/Mentoria DIO/mentoria-dio/api/_volumes/mysql/data:/var/lib/mysql
      - D:/Eduzz/Mentoria DIO/mentoria-dio/api/_volumes/mysql/conf.d:/etc/mysql/conf.d
      ## Para Linux/Mac, caminho relativo basta
      #- ./_volumes/mysql/data:/var/lib/mysql
      #- ./_volumes/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example